export const verificationArrayIndoex = [
  {
    name: "Website",
    img: "../../assets/images/globe.svg",
    placeholder: "Enter URL",
    arr: [
      { id: 1, name: "https://www.indoex.io/" },
      { id: 2, name: "www.indoex.io/" },
      { id: 4, name: "indoex.io/" },
      { id: 3, name: "https://www.international.indoex.io/" },
      { id: 1, name: "https://www.indoex.io" },
      { id: 2, name: "www.indoex.io" },
      { id: 4, name: "indoex.io" },
    ],
  },
  {
    name: "Twitter",
    img: "../../assets/images/twitter.svg",
    placeholder: "Twitter ID",
    arr: [
      { id: 1, name: "https://twitter.com/indoexsupport" },
      { id: 2, name: "https://twitter.com/indoex_ltd" },
      { id: 1, name: "https://twitter.com/indoexsupport/" },
      { id: 2, name: "https://twitter.com/indoex_ltd/" },
      { id: 3, name: "@indoexsupport" },
      { id: 4, name: "@indoex_ltd" },
      { id: 3, name: "indoexsupport" },
      { id: 4, name: "indoex_ltd" },
    ],
  },
  {
    name: "Telegram",
    img: "../../assets/images/telegram.svg",
    placeholder: "Telegram ID",
    arr: [
      { id: 1, name: "mitchell_indoex" },
      { id: 2, name: "https://t.me/mitchell_indoex" },
      { id: 3, name: "daniel_indoex" },
      { id: 3, name: "@daniel_indoex" },
      { id: 4, name: "https://t.me/daniel_indoex" },
      { id: 5, name: "cryptotechie" },
      { id: 5, name: "@cryptotechie" },
      { id: 6, name: "https://t.me/cryptotechie" },
      { id: 7, name: "katherine_william" },
      { id: 7, name: "@katherine_william" },
      { id: 8, name: "https://t.me/katherine_william" },
      { id: 9, name: "https://t.me/indoex_listings" },
      { id: 10, name: "indoex_listings" },
      { id: 10, name: "@indoex_listings" },
      { id: 11, name: "gracenorth" },
      { id: 11, name: "@gracenorth" },
      { id: 12, name: "https://t.me/gracenorth" },
      { id: 13, name: "rebecca_william_crypto" },
      { id: 13, name: "@rebecca_william_crypto" },
      { id: 14, name: "https://t.me/rebecca_william_crypto" },
      { id: 15, name: "https://t.me/rickymartin_indoex_listing_team" },
      { id: 16, name: "rickymartin_indoex_listing_team" },
      { id: 16, name: "@rickymartin_indoex_listing_team" },
      { id: 17, name: "ronnyhobbscrypto" },
      { id: 17, name: "@ronnyhobbscrypto" },
      { id: 18, name: "https://t.me/ronnyhobbscrypto" },
      { id: 19, name: "https://t.me/stephbtc" },
      { id: 20, name: "stephbtc" },
      { id: 20, name: "@stephbtc" },
      { id: 21, name: "https://t.me/kriticrypto" },
      { id: 22, name: "kriticrypto" },
      { id: 22, name: "@kriticrypto" },
      { id: 23, name: "https://t.me/leojaxom_indoex" },
      { id: 24, name: "leojaxom_indoex" },
      { id: 24, name: "@leojaxom_indoex" },
      { id: 25, name: "https://t.me/mike_indoex" },
      { id: 26, name: "mike_indoex" },
      { id: 26, name: "@mike_indoex" },
      { id: 27, name: "https://t.me/devinpaxton_indoex" },
      { id: 28, name: "devinpaxton_indoex" },
      { id: 28, name: "@devinpaxton_indoex" },
      { id: 29, name: "https://t.me/walker_indoex" },
      { id: 30, name: "walker_indoex" },
      { id: 30, name: "@walker_indoex" },
      { id: 31, name: "https://t.me/indoexlover" },
      { id: 32, name: "indoexlover" },
      { id: 32, name: "@indoexlover" },
    ],
  },
  {
    name: "Linkedin",
    img: "../../assets/images/linkedin.svg",
    placeholder: "LinkedIn ID",
    arr: [
      { id: 1, name: "https://www.linkedin.com/company/15804956/admin/" },
      { id: 1, name: "https://www.linkedin.com/company/15804956/admin" },
    ],
  },
  {
    name: "Email",
    img: "../../assets/images/mail.svg",
    placeholder: "Enter mail ID",
    arr: [
      { id: 1, name: "info@indoex.io" },
      { id: 2, name: "daniel@indoex.io" },
      { id: 3, name: "katherine@indoex.io" },
      { id: 4, name: "billy@indoex.io" },
      { id: 5, name: "gracenorth@indoex.io" },
      { id: 6, name: "support@indoex.io" },
      { id: 7, name: "relations@indoex.io" },
      { id: 7, name: "listings@indoex.io" },
    ],
  },
  {
    name: "Instagram",
    img: "../../assets/images/insta.svg",
    placeholder: "Enter Instagram ID",
    arr: [
      { id: 1, name: "https://www.instagram.com/indoex.io" },
      { id: 1, name: "https://www.instagram.com/indoex.io/" },
    ],
  },
  {
    name: "Facebook",
    img: "../../assets/images/fb.svg",
    placeholder: "Facebook mail ID",
    arr: [
      { id: 1, name: "https://www.facebook.com/indoex.official" },
      { id: 1, name: "https://www.facebook.com/indoex.official/" },
    ],
  },
];
